/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pochette.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pochette.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.563, 0, -0.358]} rotation={[-Math.PI / 2, 0, 0.594]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.103, 1.045, 0.58]}>
            <group position={[-0.001, 0, 1.105]} rotation={[0, -0.598, -Math.PI / 2]}>
              <mesh geometry={nodes.Object_10.geometry} material={materials['Translucent.001']} />
              <mesh geometry={nodes.Object_11.geometry} material={materials['Cover.001']} />
            </group>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Rough_Plastic.001']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['Translucent.001']} />
            <mesh geometry={nodes.Object_6.geometry} material={materials['White.001']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['FileBase.001']} />
          </group>
        </group>
      </group>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0.355, 1.04, -0.041]} rotation={[1.572, -0.001, -1.561]} />
    </group>
  )
}

useGLTF.preload('/pochette.glb')
