/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/disque.glb 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei';
import * as THREE from 'three';

function Disque({ textureURL, ...props }) {
  const { nodes, materials } = useGLTF('/models/disque.glb')

 

  return (
    <group {...props} dispose={null}>
      <group position={[-0.004, 0, -0.005]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={1.022}>
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/disque.glb')

export default Disque
